### PR TITLE
update developer email

### PR DESCRIPTION
**Pull request by pmgrove**
:v:

/cc @zendesk/vegemite
### Description

Updated developer email address as we shouldn't use support@zendesk.com for any apps except official public Zendesk apps.
### References
- JIRA: n/a
### Risks
- None

### CODE REVIEW

**Comment by sandlerr** [comment]
:+1:

**Comment by sandlerr** [comment]
merge?

**Comment by pmgrove** [comment]
@sandlerr, can we move this repo to zendesklabs?

**Comment by sandlerr** [comment]
this one already is in labs too

**Pull request merged**
